include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    prefer_final_locals: true
    avoid_dynamic_calls: true
    require_trailing_commas: true
    always_declare_return_types: true
